name: floox
description: A small flutter scaffold tool.include statemanagement, screen adapter, l10n, build_runner and etc. 
version: 0.1.0
homepage: https://github.com/laiiihz/floox

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.0
  dart_style: ^2.0.0
  grinder: ^0.9.0
  path: ^1.8.0
dev_dependencies: 
  pedantic: ^1.11.0

# dev_dependencies:

